-- CreateTable
CREATE TABLE "Estado" (
    "EST_ID" TEXT NOT NULL,
    "EST_DSC" BOOLEAN NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Estado_pkey" PRIMARY KEY ("EST_ID")
);

-- CreateTable
CREATE TABLE "Usuario" (
    "USU_ID" TEXT NOT NULL,
    "USU_USR" TEXT NOT NULL,
    "USU_PSS" TEXT NOT NULL,
    "USU_NOM" TEXT NOT NULL,
    "USU_APA" TEXT NOT NULL,
    "USU_AMA" TEXT NOT NULL,
    "USU_TEL" INTEGER NOT NULL,
    "PRF_ID" TEXT NOT NULL,
    "ARR_ADQ_ID" TEXT,
    "ARR_ACT_ID" TEXT,
    "EST_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Usuario_pkey" PRIMARY KEY ("USU_ID")
);

-- CreateTable
CREATE TABLE "Perfil" (
    "PRF_ID" TEXT NOT NULL,
    "PRF_NOM" TEXT NOT NULL,
    "PRF_DSC" TEXT NOT NULL,
    "EST_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Perfil_pkey" PRIMARY KEY ("PRF_ID")
);

-- CreateTable
CREATE TABLE "Comando" (
    "CMD_ID" TEXT NOT NULL,
    "CMD_CODE" INTEGER NOT NULL,
    "CMD_DSC" TEXT NOT NULL,
    "ARR_ID" TEXT,
    "EST_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Comando_pkey" PRIMARY KEY ("CMD_ID")
);

-- CreateTable
CREATE TABLE "Arreglo" (
    "ARR_ID" TEXT NOT NULL,
    "ARR_ADQ_ID" TEXT,
    "ARR_ACT_ID" TEXT,
    "EST_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Arreglo_pkey" PRIMARY KEY ("ARR_ID")
);

-- CreateTable
CREATE TABLE "Arreglo_Adquirido" (
    "ARR_ADQ_ID" TEXT NOT NULL,
    "EST_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Arreglo_Adquirido_pkey" PRIMARY KEY ("ARR_ADQ_ID")
);

-- CreateTable
CREATE TABLE "Arreglo_Activo" (
    "ARR_ACT_ID" TEXT NOT NULL,
    "EST_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Arreglo_Activo_pkey" PRIMARY KEY ("ARR_ACT_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "Estado_EST_DSC_key" ON "Estado"("EST_DSC");

-- CreateIndex
CREATE UNIQUE INDEX "Usuario_USU_USR_key" ON "Usuario"("USU_USR");

-- CreateIndex
CREATE UNIQUE INDEX "Perfil_PRF_NOM_key" ON "Perfil"("PRF_NOM");

-- CreateIndex
CREATE UNIQUE INDEX "Comando_CMD_CODE_key" ON "Comando"("CMD_CODE");

-- AddForeignKey
ALTER TABLE "Usuario" ADD CONSTRAINT "Usuario_PRF_ID_fkey" FOREIGN KEY ("PRF_ID") REFERENCES "Perfil"("PRF_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Usuario" ADD CONSTRAINT "Usuario_ARR_ADQ_ID_fkey" FOREIGN KEY ("ARR_ADQ_ID") REFERENCES "Arreglo_Adquirido"("ARR_ADQ_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Usuario" ADD CONSTRAINT "Usuario_ARR_ACT_ID_fkey" FOREIGN KEY ("ARR_ACT_ID") REFERENCES "Arreglo_Activo"("ARR_ACT_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Usuario" ADD CONSTRAINT "Usuario_EST_ID_fkey" FOREIGN KEY ("EST_ID") REFERENCES "Estado"("EST_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Perfil" ADD CONSTRAINT "Perfil_EST_ID_fkey" FOREIGN KEY ("EST_ID") REFERENCES "Estado"("EST_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Comando" ADD CONSTRAINT "Comando_ARR_ID_fkey" FOREIGN KEY ("ARR_ID") REFERENCES "Arreglo"("ARR_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Comando" ADD CONSTRAINT "Comando_EST_ID_fkey" FOREIGN KEY ("EST_ID") REFERENCES "Estado"("EST_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Arreglo" ADD CONSTRAINT "Arreglo_ARR_ADQ_ID_fkey" FOREIGN KEY ("ARR_ADQ_ID") REFERENCES "Arreglo_Adquirido"("ARR_ADQ_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Arreglo" ADD CONSTRAINT "Arreglo_ARR_ACT_ID_fkey" FOREIGN KEY ("ARR_ACT_ID") REFERENCES "Arreglo_Activo"("ARR_ACT_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Arreglo" ADD CONSTRAINT "Arreglo_EST_ID_fkey" FOREIGN KEY ("EST_ID") REFERENCES "Estado"("EST_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Arreglo_Adquirido" ADD CONSTRAINT "Arreglo_Adquirido_EST_ID_fkey" FOREIGN KEY ("EST_ID") REFERENCES "Estado"("EST_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Arreglo_Activo" ADD CONSTRAINT "Arreglo_Activo_EST_ID_fkey" FOREIGN KEY ("EST_ID") REFERENCES "Estado"("EST_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
